### PR TITLE
feat(glider.js): add aria-disabled attribute

### LINKED ISSUE #148: Feature: aria-disable attributes
- add aria-disabled attributes when buttons are disabled, voice over will not pickup that, it has `disabled` state, for more info see [aria-disabled example](https://a11y-101.com/development/aria-disabled)

### PR DESCRIPTION
**Pull request by tomasvn**
- better usability with screen reader
- Fixes #148

### CODE REVIEW

**Comment by tomasvn** [comment]
The packaged needed to be re-minified and published again on npm :) I have updated only the main file, and didn't run minify

**Comment by NickPiscitelli** [comment]
Hi tomasvn,

Thanks for the fix, this looks good!

In striving to keep the code size as minimal as possible, can you abstract this to a function and swap the logic to a ternary. This will cut down on the byte size of the plugin (ideally trying to keep <3k)

In regards to the minification, there are task runners in the repository for that. If you run `npm install --save-dev` before committing, it will handle the minification via Git hooks.

Also, why was the `rewind` default changed?

**Comment by tomasvn** [comment]
I was testing the functionality, if the prop is being added and by mistake I have pushed the changed default rewind the html too

**Comment by tomasvn** [comment]
@NickPiscitelli I have change the default `rewind` value back to `true` and changed from if/else to ternary

**Pull request merged**
