### PR TITLE
Enable improved progressive enhancement by replacing width for minWidth

### PR DESCRIPTION
**Pull request by kevinfarrugia**
At the moment, before the Glider is initialised, the items in the glider-contain do not appear correct and are shifted as the Glider loads.

demo

The user can choose to:
- Incur [a layout shift](https://web.dev/cls/)
- Not show the content until the Glider has initialized

This problem could be solved by replacing `width` by `min-width`.

I created a simplified Codepen illustrating the issue:
- Using width: https://codepen.io/kevinfarrugia/pen/KKQxGwz
- Using min-width: https://codepen.io/kevinfarrugia/pen/MWQqQVE

Using `min-width` instead of `width` means that the content will not be shrunk to fit the width of the container. As a result, if you were using `margin`, these margins are not factored in when calculating the `_itemWidth`

```
    _.itemWidth = _.opt.exactWidth
      ? _.opt.itemWidth
      : _.containerWidth / _.opt.slidesToShow;
```

This may be mitigated using `getComputedStyle` to deduct the margins from the `minWidth` property, however this may cause a [layout reflow or style recalc](https://gist.github.com/paulirish/5d52fb081b3570c81e3a#calling-getcomputedstyle).

```
      __.style.minWidth =
        _.itemWidth -
        computedStyle.marginLeft -
        computedStyle.marginRight +
        'px'
```

PR includes the solution and a demo illustrating the solution.

### CODE REVIEW

**Comment by kevinfarrugia** [comment]
@NickPiscitelli do you think this is something you are able to review please?

**Comment by NickPiscitelli** [comment]
Hi Kevin,

Sorry for the delay. Checking this out now, but so far it looks good. Thanks for the detailed PR, it's really appreciated.

**Comment by NickPiscitelli** [comment]
This looks great, but I have two questions:

1. Why swap to the CSS `calc()` block for the min-width value? This is slower than setting directly via JS like you were doing originally (although I would remove the implicit casting on concatenation; could have odd behavior in different engines)

2. Any reason to not continue setting `width`? I think this should be kept for backwards compatible reasons since it would stop overriding that rule for any existing styles.

**Comment by NickPiscitelli** [comment]
Also, what are your thoughts on this being configurable due to the layout shift concern. For most cases, a simple min width set to 90% of the item width would suffice and it could be an option.

**Comment by kevinfarrugia** [comment]
Sorry I haven't had the chance to look into it yet. Will take a look and get back to you.

**Comment by kevinfarrugia** [comment]
In hindsight, it is probably easier for the developer using the library to fix this using CSS on their end. For example by adding the `min-width` style attribute or a `height` attribute on the `glider-track`. This would then be overridden once GliderJS is initialized, but there would be no visible layout shift.

**Pull request closed without merging**
